# Generated by Django 4.2 on 2024-02-08 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_id', models.CharField(max_length=10)),
                ('tab_label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.JSONField()),
                ('text', models.TextField()),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='speciality.speciality')),
            ],
            options={
                'verbose_name_plural': 'Content',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('card_text', models.TextField()),
                ('image', models.ImageField(upload_to='images/card_images/')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='speciality.content')),
            ],
            options={
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
