# Generated by Django 5.0.2 on 2024-04-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='link',
        ),
    ]
