# Generated by Django 5.0.2 on 2024-04-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speciality', '0002_alter_card_options_alter_content_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_text',
            field=models.TextField(verbose_name='Описание карточки'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='images/card_images/', verbose_name='Изображение для карточки'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название Карточки'),
        ),
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.CharField(max_length=255, verbose_name='Размер и цвет тега'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.TextField(verbose_name='Название специальности'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='tab_id',
            field=models.CharField(max_length=10, verbose_name='Номер академической степени'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='tab_label',
            field=models.CharField(max_length=255, verbose_name='Название академической степени'),
        ),
    ]
