# Generated by Django 5.0.2 on 2024-04-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='MapPointer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary', models.CharField(max_length=255, verbose_name='Зарплата')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professions', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Метка на карте',
                'verbose_name_plural': 'Метки на карте',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название карточки')),
                ('text', models.TextField(verbose_name='Текст карточки')),
                ('image', models.ImageField(upload_to='card_images/', verbose_name='Фото карточки')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professions', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promo_images/', verbose_name='Фото промо')),
                ('description', models.TextField(verbose_name='Описание профессии')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professions', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Промо',
                'verbose_name_plural': 'Промо',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_degree', models.CharField(max_length=255, verbose_name='Академическая степень')),
                ('name', models.CharField(max_length=255, verbose_name='Название специальности')),
                ('faculty', models.CharField(max_length=255, verbose_name='Факультет')),
                ('budget_places_count', models.IntegerField(verbose_name='Бюджетные места')),
                ('year_budget_places_count', models.IntegerField(null=True, verbose_name='Год бюджетных мест')),
                ('passing_score', models.IntegerField(verbose_name='Количество мест')),
                ('year_passing_score', models.IntegerField(null=True, verbose_name='Год количества мест')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена обучения')),
                ('year_price', models.IntegerField(null=True, verbose_name='Год цены обучения')),
                ('period', models.IntegerField(verbose_name='Период обучения')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professions', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Академическая степень',
                'verbose_name_plural': 'Академические степени',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя тэга')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professions', verbose_name='Профессия')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название Задачи')),
                ('text', models.TextField(verbose_name='Текст задачи')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professions', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
