# Generated by Django 5.0.2 on 2024-03-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='description',
        ),
        migrations.RemoveField(
            model_name='map',
            name='pointers',
        ),
        migrations.RemoveField(
            model_name='map',
            name='price',
        ),
        migrations.RemoveField(
            model_name='map',
            name='title',
        ),
        migrations.AddField(
            model_name='speciality',
            name='year_budget_places_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='year_passing_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='speciality',
            name='year_price',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='MapPointer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_min', models.CharField(max_length=255)),
                ('price_max', models.CharField(max_length=255)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointers', to='professions.map')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professions')),
            ],
        ),
    ]
