# Generated by Django 5.0.2 on 2024-03-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0002_remove_map_description_remove_map_pointers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Карта', 'verbose_name_plural': 'Карты'},
        ),
        migrations.AlterModelOptions(
            name='mappointer',
            options={'verbose_name': 'Поинтер', 'verbose_name_plural': 'Поинтеры'},
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'verbose_name': 'Промо', 'verbose_name_plural': 'Промо'},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Академическая степень', 'verbose_name_plural': 'Академические степени'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
