# Generated by Django 5.0.2 on 2024-03-02 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0003_alter_card_options_alter_map_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='title',
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='card_images/', verbose_name='Фото карточки'),
        ),
        migrations.AlterField(
            model_name='card',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professions', verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(verbose_name='Текст карточки'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название карточки'),
        ),
        migrations.AlterField(
            model_name='map',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professions', verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='mappointer',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mappointer',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointers', to='professions.map', verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='mappointer',
            name='price_max',
            field=models.CharField(max_length=255, verbose_name='Максимальная цена'),
        ),
        migrations.AlterField(
            model_name='mappointer',
            name='price_min',
            field=models.CharField(max_length=255, verbose_name='Минималная цена'),
        ),
        migrations.AlterField(
            model_name='mappointer',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='description',
            field=models.TextField(verbose_name='Описание профессии'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='image',
            field=models.ImageField(upload_to='promo_images/', verbose_name='Фото промо'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professions', verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='academic_degree',
            field=models.CharField(max_length=255, verbose_name='Академическая степень'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='budget_places_count',
            field=models.IntegerField(verbose_name='Бюджетные места'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='faculty',
            field=models.CharField(max_length=255, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название специальности'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='passing_score',
            field=models.IntegerField(verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='period',
            field=models.IntegerField(verbose_name='Период обучения'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена обучения'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professions', verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='year_budget_places_count',
            field=models.IntegerField(null=True, verbose_name='Год бюджетных мест'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='year_passing_score',
            field=models.IntegerField(null=True, verbose_name='Год количества мест'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='year_price',
            field=models.IntegerField(null=True, verbose_name='Год цены обучения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professions', verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(verbose_name='Текст задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название Задачи'),
        ),
    ]
