# Generated by Django 5.0.2 on 2024-03-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0004_remove_promo_title_alter_card_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mappointer',
            options={'verbose_name': 'Метка на карте', 'verbose_name_plural': 'Метки на карте'},
        ),
    ]
