# Generated by Django 5.0.2 on 2024-04-12 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0004_bakalavr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magistr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=255, verbose_name='Название факультета')),
                ('speciality_name', models.CharField(max_length=255, verbose_name='Название специальности')),
                ('link', models.URLField(verbose_name='Ссылка на специальность')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professions', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Магистратура',
                'verbose_name_plural': 'Магистратура',
            },
        ),
    ]
