# Generated by Django 5.0.2 on 2024-03-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0005_alter_mappointer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='faculty',
        ),
        migrations.AddField(
            model_name='speciality',
            name='tags',
            field=models.JSONField(null=True, verbose_name='Факультет'),
        ),
    ]
