# Generated by Django 5.0.2 on 2024-04-02 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0006_remove_speciality_faculty_speciality_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Необходимый навык', 'verbose_name_plural': 'Необходимые навыки'},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Карьерный путь', 'verbose_name_plural': 'Карьерные пути'},
        ),
        migrations.AlterModelOptions(
            name='professions',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Название профессии'},
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'verbose_name': 'Описание професии', 'verbose_name_plural': 'Описание професии'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Основная задача', 'verbose_name_plural': 'Основные задачи'},
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='budget_places_count',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='passing_score',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='period',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='price',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='year_budget_places_count',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='year_passing_score',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='year_price',
        ),
        migrations.AddField(
            model_name='speciality',
            name='faculty',
            field=models.CharField(max_length=255, null=True, verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='links_speciality',
            field=models.URLField(null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professions', verbose_name='Название профессии'),
        ),
    ]
