# Generated by Django 5.0.2 on 2024-04-12 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0007_hhvacancy_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ссылки')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professions.professions', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Полезная ссылка',
                'verbose_name_plural': 'Полезные ссылки',
            },
        ),
    ]
